language: python
python:
- 2.7
services:
- docker
before_install:
- sudo apt-get update
- docker-compose --version
- pip install docker-compose --upgrade
- docker-compose --version
install:
- cd v2_3_0
- docker-compose build
- docker-compose up -d
- docker-compose ps
before_script:
- pip install requests
- pip install docker
- cd $TRAVIS_BUILD_DIR
script:
- python tests.py
notifications:
  slack:
    rooms:
    - optimum-team:GycletOWK4Kt95GktwYwfUMp#build
after_success:
- cd v2_3_0
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- docker-compose -f docker-compose-build.yml images
- docker push trydirect/magento:2.3.0
env:
  global:
  - secure: GtdbVulklByi5s4NrZMfV/0jnLxr5qKwF//sZQpM4BUwqClg+GKZP+dBWFTuOwctFXusqK9JSHr5cdTUpyTVqklFPnddFdtvaOgDAGD9Vq1LhEzfPi8Ba85moCiOGohcIs4zCrGOh88FME3ty6vwHmTnZ+4SvGP7cdFjj1eFbhb7Q8JiI7gIN2jPAE/0+98vOWx0fzxGqov6slcE4gqckpQ6k2vIcGt35zP1m9yFKiKFAprsfsExHuWa3qWUavLZEhZjEoQNaGfimyPM5iLGXIFkxysXzGVZsMM7E7uL9EzMn56XouyCnluYpmn0qAy3RAYXMgVkpUndR5hIPNYcCgZAhM6ubiSYWaoWTgy4pm7l2s9ZG1hlFHPhZEvSkyoSmHpj8VxpCXguMMXnCuJLBhIhQqhsQRP28Fj0S1Mpe1K8x2+9w1mzOGPwhlVmt3uTc9M4/TfpCwA2pwp0rXgY0uz3A7bR/2jM+nygMHDSBjXjGqYl/I+yLsS0qLCCmu8quPP7b8BpmJZly73+eW05OjrNOo4PA+X7rkjRKwhl1Ddbev3TAJzGgvacsuGd8zA37zmlZRCSsFTp3WX/1fzcqfQmX3roxCkADnQ8ccz0edjjeZ8No0h2Hpq85pcZ7JxFaqPD40rNDd9Zpe+kqXhiJs63gEvJ7/MLUAEVU328pK4=
  - secure: s+/7wWjncrZJpJCPB5PPbIWvq0R3568z0z7aaCWuThS0KlGFtB60iMSrZl3gRqkGRT9yp3oH6m3En0JURrrWSO0xxCHnyWOCQI82gYy0bE+NaO0MsHJ9C/YUm9/KX+fQsaYoomD8t8pyRUXVULLYCMgpS+qa0nnCYbBjOAdUiemArkg4XabtIoKXpE10RV7KPQp/NJKgnPt5vexTDxCA48QtY4Q9d/iUJBTHz+dTdOhDiuIWVUMW+HtBCnztkSqdD1daJUz6EWauJY/Ioj0CYbr9Rv87eD19KPRnV0CPZ8+lVxiFzIu4HUOI8sVJmUYEvK1bGT9SLmadbzooEI2bDagw5BfAvd8LwDqtWCghoO/AAn1cQMajYKn854EJfFDNL93bKKy/daBy1k1mSSyN8GMGR/ocMvHmBZsjpLq3E1fkvvACUhsjNbBcUAEcIRCVa7sFV2SFjNis0e07bgGvfaIDOfGDQyS7XJEFU5AZ8pYw2zE9kGGf+CShSVwBMZ3ZQpv4q3jja3cjy/QTXjjmy9z9OrJEsJD9yrxDTbR4vzzaXbj7chCrNGP4FlG87nACBYacmub2tc9axAT9RRMCqrjR9gHZ/Uy5mhg6mO+c3mLbu1PFBOf/tr4OzzTXkSMUs+NR7QRSFdhX5Okhvt+lc39H8joEcIzvNUSR4SSq//0=
