version: '2'

volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local

services:
  magento:
    image: trydirect/magento:2.3.2
    build: dockerfiles/build/apache
    container_name: magento
    env_file:
      .env
    volumes:
      - /var/www
      - magento_data:/data
    depends_on:
      - mariadb
    working_dir: /var/www/magento2

  mariadb:
    image: "mariadb:latest"
    container_name: magento_mariadb
    env_file:
      .env
    volumes:
      - "mariadb_data:/var/lib/mysql"

  nginx:
    image: trydirect/nginx
    container_name: nginx
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/certs/ssl:/etc/ssl/nginx
      - ./configs/certs/letsencrypt:/etc/letsencrypt
      - ./configs/cron/nginx:/var/spool/cron/crontabs
      - ./configs/nginx/conf.d:/etc/nginx/conf.d/
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/supervisord/nginx.conf:/etc/supervisor/conf.d/nginx.conf
    links:
      - magento
    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n
